In [2]:
import numpy as np

In [3]:
# Using np.newaxis

arr1d = np.array([1, 2, 3, 4, 5])

# EXERCISE 1: Understanding np.newaxis
# Starting array
arr1d = np.array([1, 2, 3, 4, 5])
print("Original shape:", arr1d.shape)
print("Original array:\n", arr1d)

# TODO: Add a new axis at position 0 (makes it a row vector)
# Expected shape: (1, 5)
arr_row = arr1d[:, np.newaxis]
print("\nRow vector shape:", arr_row.shape)
print("Row vector:\n", arr_row)

# TODO: Add a new axis at position 1 (makes it a column vector)
# Expected shape: (5, 1)
arr_col = arr1d[np.newaxis, :]
print("\nColumn vector shape:", arr_col.shape)
print("Column vector:\n", arr_col)


Original shape: (5,)
Original array:
 [1 2 3 4 5]

Row vector shape: (5, 1)
Row vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]

Column vector shape: (1, 5)
Column vector:
 [[1 2 3 4 5]]


In [4]:
# EXERCISE 2: Broadcasting with np.newaxis
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])

# TODO: Reshape 'a' and 'b' using np.newaxis to make them broadcastable
# Goal: Add a column to 'a' and a row to 'b' so you can compute a 3x4 matrix
# Expected result shape: (3, 4)
# Hint: a should become (3, 1) and b should become (1, 4)

a_reshaped = a[:, np.newaxis]
b_reshaped = b[np.newaxis, :]
result = a_reshaped + b_reshaped  # This should broadcast to (3, 4)

print("Result shape:", result.shape)
print("Result:\n", result)


Result shape: (3, 4)
Result:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [5]:
# EXERCISE 3: Matrix multiplication preparation
# You have a 1D array that represents a single data point with 3 features
features = np.array([0.5, 0.8, 0.3])

# TODO: Convert this to a column vector (1 sample, 3 features) for matrix multiplication
# Expected shape: (1, 3)
# This format is needed when multiplying with weights: (1, 3) @ (3, 4) = (1, 4)
features_matrix = features[np.newaxis, :]  # Your solution

print("Features shape:", features_matrix.shape)
print("Features:\n", features_matrix)

# Now test matrix multiplication with a weight matrix
weights = np.random.randn(3, 4)
output = features_matrix @ weights
print("\nOutput shape:", output.shape)  # Should be (1, 4)


Features shape: (1, 3)
Features:
 [[0.5 0.8 0.3]]

Output shape: (1, 4)


In [6]:
# EXERCISE 4: Multiple dimensions
arr_2d = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
print("Original shape:", arr_2d.shape)

# TODO: Add a new axis at position 0 to make it (1, 2, 2)
arr_3d_1 = arr_2d[np.newaxis, :, :]  # Your solution

# TODO: Add a new axis at position 2 to make it (2, 2, 1)
arr_3d_2 = arr_2d[:, :, np.newaxis]

print("\nAfter adding axis at position 0:", arr_3d_1.shape)
print("After adding axis at position 2:", arr_3d_2.shape)

# SOLUTION:
# arr_3d_1 = arr_2d[np.newaxis, :, :]  # or arr_2d[None, :, :]
# arr_3d_2 = arr_2d[:, :, np.newaxis]

Original shape: (2, 2)

After adding axis at position 0: (1, 2, 2)
After adding axis at position 2: (2, 2, 1)


In [7]:
# EXERCISE 5: Real-world example - preparing batch data
# You have multiple data points, each with 2 features
data = np.array([[1, 2], [3, 4], [5, 6]])  # 3 samples, 2 features each
print("Original data shape:", data.shape)  # (3, 2)

# TODO: Add a batch dimension at position 0 to make it (1, 3, 2)
# This simulates having a batch of size 1 containing 3 samples
batch_data = data[np.newaxis, :, :]  # Your solution

print("Batch data shape:", batch_data.shape)


Original data shape: (3, 2)
Batch data shape: (1, 3, 2)


In [8]:
pos = 10
np.arange(pos)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
d = 22
np.arange(d)[np.newaxis, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21]])