In [4]:
import numpy as np




In [5]:
np.random.seed(1)
a = np.random.randn(3, 2)
a, a.shape


(array([[ 1.62434536, -0.61175641],
        [-0.52817175, -1.07296862],
        [ 0.86540763, -2.3015387 ]]),
 (3, 2))

In [6]:
a[:,:1]


array([[ 1.62434536],
       [-0.52817175],
       [ 0.86540763]])

In [7]:
np.random.seed(1)
a = np.random.randn(3, 2, 4)
a, a.shape


(array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
         [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ]],
 
        [[ 0.3190391 , -0.24937038,  1.46210794, -2.06014071],
         [-0.3224172 , -0.38405435,  1.13376944, -1.09989127]],
 
        [[-0.17242821, -0.87785842,  0.04221375,  0.58281521],
         [-1.10061918,  1.14472371,  0.90159072,  0.50249434]]]),
 (3, 2, 4))

In [8]:
x1,x2,x3 = a.shape
x1,x2,x3

(3, 2, 4)

In [9]:
a[:,:,0]

array([[ 1.62434536,  0.86540763],
       [ 0.3190391 , -0.3224172 ],
       [-0.17242821, -1.10061918]])

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
c = np.random.randn(3, 2)
a = np.random.randn(4, 2)
x = np.concatenate((c, a), axis=0)
c,a,x

(array([[ 0.90085595, -0.68372786],
        [-0.12289023, -0.93576943],
        [-0.26788808,  0.53035547]]),
 array([[-0.69166075, -0.39675353],
        [-0.6871727 , -0.84520564],
        [-0.67124613, -0.0126646 ],
        [-1.11731035,  0.2344157 ]]),
 array([[ 0.90085595, -0.68372786],
        [-0.12289023, -0.93576943],
        [-0.26788808,  0.53035547],
        [-0.69166075, -0.39675353],
        [-0.6871727 , -0.84520564],
        [-0.67124613, -0.0126646 ],
        [-1.11731035,  0.2344157 ]]))

In [12]:
np.square(np.array([[1,2],[3,4]]))


array([[ 1,  4],
       [ 9, 16]])

In [16]:
a = np.array([[1,2],[3,4]])
print(a)
np.clip(a, 0, 1, out = a)
print(a)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [82]:
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

# Original probability distribution
probs = np.array([0.1, 0.4, 0.3, 0.2])
char_to_ix = {'\n': 0, 'a': 1, 'b': 3, 'c': 4}
num_samples = 100
sorted(char_to_ix.values())


[0, 1, 3, 4]

In [89]:
[None] + [2,3,4,5]

[None, 2, 3, 4, 5]

In [ ]:
# Generate 100 samples based on the weighted probabilities
samples = np.random.choice(['a', 'b', 'c', 'd'], size=num_samples, p=probs)

# Count the occurrences of each sampled index
counts = Counter(samples)

# Prepare data for plotting, ensuring all indices are present
labels = list(indices)
values = [counts.get(i, 0) for i in labels]

# Create the bar chart to illustrate the distribution
plt.figure(figsize=(8, 5))
plt.bar(labels, values, tick_label=labels)
plt.xlabel("Index")
plt.ylabel(f"Frequency (out of {num_samples} samples)")
plt.title("Distribution of Weighted Random Samples")
plt.xticks(labels)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print(f"Sampled counts: {dict(sorted(counts.items()))}")