In [2]:
import numpy as np
import tensorflow as tf


In [3]:
x = tf.constant([[7., 6., 0., 0., 1.], [1., 2., 3., 0., 0.], [0., 0., 0., 4., 5.]])

x, \
tf.cast(tf.math.equal(x, 0), tf.float32), \
1 - tf.cast(tf.math.equal(x, 0), tf.float32)

2025-11-01 19:13:33.191446: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Max
2025-11-01 19:13:33.191507: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 48.00 GB
2025-11-01 19:13:33.191515: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 18.72 GB
2025-11-01 19:13:33.191551: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-11-01 19:13:33.191563: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


(<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[7., 6., 0., 0., 1.],
        [1., 2., 3., 0., 0.],
        [0., 0., 0., 4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[0., 0., 1., 1., 0.],
        [0., 0., 0., 1., 1.],
        [1., 1., 1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[1., 1., 0., 0., 1.],
        [1., 1., 1., 0., 0.],
        [0., 0., 0., 1., 1.]], dtype=float32)>)

In [4]:
x = tf.random.uniform((1, 3))
print(x, x.shape)

o = tf.ones((1, 3, 3))
print(o)

tf.linalg.band_part(o, -1, 0)


tf.Tensor([[0.3457631  0.5554755  0.71517265]], shape=(1, 3), dtype=float32) (1, 3)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 3, 3), dtype=float32)


<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]]], dtype=float32)>

In [5]:
a = tf.random.uniform((3, 4))
b = tf.random.uniform((2, 4))
m = tf.matmul(a, b, transpose_b=True)
m


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.4185346, 1.0333495],
       [1.9171546, 1.4640734],
       [1.5057828, 1.0159649]], dtype=float32)>

In [6]:
logits = tf.constant([[1. , 1.5, 0.5, 0.5],
                      [1. , 1. , 1. , 0.5],
                      [1. , 1. , 0. , 0.5]], dtype=tf.float32)

mask = tf.constant([[[1, 1, 0, 1],
                     [1, 1, 0, 1],
                     [1, 1, 0, 1]]], dtype=tf.float32)

logits_masked = logits + (1.0 - mask) * -1e9

tf.nn.softmax(logits_masked, axis=-1)




<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0.3071959 , 0.5064804 , 0.        , 0.18632373],
        [0.38365173, 0.38365173, 0.        , 0.23269655],
        [0.38365173, 0.38365173, 0.        , 0.23269655]]], dtype=float32)>

In [24]:
pos = 10
d = 24
i = np.arange(d)[np.newaxis, :]//2
pos = np.arange(pos)[:, np.newaxis]
print(pos)
print(i)
angles = pos / np.power(10000, (2 *i )/d)
print(angles)








[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00000000e+00 1.00000000e+00 4.64158883e-01 4.64158883e-01
  2.15443469e-01 2.15443469e-01 1.00000000e-01 1.00000000e-01
  4.64158883e-02 4.64158883e-02 2.15443469e-02 2.15443469e-02
  1.00000000e-02 1.00000000e-02 4.64158883e-03 4.64158883e-03
  2.15443469e-03 2.15443469e-03 1.00000000e-03 1.00000000e-03
  4.64158883e-04 4.64158883e-04 2.15443469e-04 2.15443469e-04]
 [2.00000000e+00 2.00000000e+00 9.28317767e-01 9.28317767e-01
  4.30886938e-01 4.30886938e-01 2.00000000e-01 2.00000000e-01
  9