<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Getting-started" data-toc-modified-id="Getting-started-1">Getting started</a></span></li><li><span><a href="#Indexing-and-slicing" data-toc-modified-id="Indexing-and-slicing-2">Indexing and slicing</a></span></li></ul></div>

In [1]:
import torch

In [2]:
# 1D tenzor
x = torch.arange(12, dtype=torch.float32)
x


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

## Getting started

In [3]:
x.numel()

12

In [4]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
# use -1 to infer size for this axis
x.reshape(-1,3)


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [6]:
# Fill with zeros, or ones
torch.zeros((2,3,4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(2,3)


tensor([[-0.4206, -0.3251,  2.2276],
        [ 0.3711,  2.1961, -0.4139]])

In [9]:
torch.tensor([[1,2],[3,4],[5,6]])


tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Indexing and slicing


In [10]:
X = torch.randint(10, (3,4))
X

tensor([[2, 2, 7, 9],
        [2, 5, 0, 3],
        [0, 9, 5, 6]])

In [11]:
X[:1]

tensor([[2, 2, 7, 9]])

In [12]:
X[-1]

tensor([0, 9, 5, 6])

In [13]:
X[-2]

tensor([2, 5, 0, 3])

In [14]:
X[1:3]

tensor([[2, 5, 0, 3],
        [0, 9, 5, 6]])

In [15]:
X[:-1, :]

tensor([[2, 2, 7, 9],
        [2, 5, 0, 3]])

In [16]:
X


tensor([[2, 2, 7, 9],
        [2, 5, 0, 3],
        [0, 9, 5, 6]])