<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Operations" data-toc-modified-id="Operations-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Operations</a></span><ul class="toc-item"><li><span><a href="#Unary-scalar-operation" data-toc-modified-id="Unary-scalar-operation-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Unary scalar operation</a></span></li><li><span><a href="#Binary-scalar-operation" data-toc-modified-id="Binary-scalar-operation-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Binary scalar operation</a></span></li><li><span><a href="#Concatenating-tensors" data-toc-modified-id="Concatenating-tensors-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Concatenating tensors</a></span><ul class="toc-item"><li><span><a href="#Constructing-tensor-from-logical-statements" data-toc-modified-id="Constructing-tensor-from-logical-statements-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Constructing tensor from logical statements</a></span></li><li><span><a href="#Summing-all-tensor's-elements" data-toc-modified-id="Summing-all-tensor's-elements-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Summing all tensor's elements</a></span></li></ul></li></ul></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Saving-memory" data-toc-modified-id="Saving-memory-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Saving memory</a></span></li><li><span><a href="#Convertion-to-other--Python-objects" data-toc-modified-id="Convertion-to-other--Python-objects-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Convertion to other  Python objects</a></span></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Exercises</a></span></li></ul></div>

In [1]:
import torch as t

# Operations


In [2]:
x = t.arange(-2, 3)
x


tensor([-2, -1,  0,  1,  2])

## Unary scalar operation

Mathemtically:
$$
f: \mathbb{R} \rightarrow \mathbb{R}
$$

Example:
$$
f: \mathbb{x} \rightarrow \mathbb{e^x}
$$

In [23]:
x, t.exp(x)


(tensor([1., 2., 3., 4.]), tensor([ 2.7183,  7.3891, 20.0855, 54.5982]))

## Binary scalar operation

Mathematically: $f: \mathbb{R}, \mathbb{R} \rightarrow \mathbb{R}$
Given vectors $\mathbf{u}$ and $\mathbf{v}$ of the same size, we produce: $\mathbf{v = F(u,v)}$

Example:


In [4]:
x = t.tensor([1.0, 2, 3, 4])
y = t.full((4,), 2)

x, y


(tensor([1., 2., 3., 4.]), tensor([2, 2, 2, 2]))

In [5]:
x + x, x - y, x * y, x / y, x ** y


(tensor([2., 4., 6., 8.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1.,  4.,  9., 16.]))

## Concatenating tensors


In [6]:
X = t.arange(12, dtype=t.float32).reshape(3, 4)
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
Y = t.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y


tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [8]:
t.cat((X, Y), dim=0)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [9]:
t.cat((X, Y), dim=1)


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

### Constructing tensor from logical statements


In [10]:
X == Y


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

### Summing all tensor's elements


In [11]:
X.sum()


tensor(66.)

# Broadcasting

Limited ability to perform bitwise operations on tensor's with different size.

2-step procedure:
1. expand one or both tensors by duplicating elements along the axes with length 1, so that after transformation the both tensors would have the same shape
2. Perfrom requested bitwise operation.

Example:


In [12]:
a = t.arange(3).reshape((3, 1))
b = t.arange(2).reshape((1, 2))
a, b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [13]:
# Shapes of `a` and `b` do not match up, however broadcasting can do this trick:

a + b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

# Saving memory

Reassigned variables leaves previously allocated objects orphan in memory.
But tensors in PyTorch are mutable. This can be leveraged to avoid uncontrolled memory consumption.
Use `T[:]` notation to write into `T` object

In [14]:
X, Y


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [15]:
Z = t.zeros_like(X)
Z, f'id(Z)={id(Z)}'


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 'id(Z)=4713368704')

In [16]:
Z[:] = X+Y
Z, f'id(Z)={id(Z)}'


(tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]),
 'id(Z)=4713368704')

In [17]:
# Or the shortcut

print(X, f'id(Z)={id(Z)}')
X += Y
print(X, f'id(Z)={id(Z)}')



tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) id(Z)=4713368704
tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]]) id(Z)=4713368704


# Convertion to other  Python objects

Converting to a NumPy tensor (ndarray), or vice versa, is easy. The torch Tensor and numpy array will share their underlying memory, and changing one through an in-place operation will also change the other.


In [18]:
A = X.numpy()
A

array([[ 2.,  2.,  6.,  6.],
       [ 5.,  7.,  9., 11.],
       [12., 12., 12., 12.]], dtype=float32)

In [19]:
t.from_numpy(A)

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])

# Exercises


In [20]:
X, Y


(tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [21]:
X == Y


tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
X < Y


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])