<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Getting-started" data-toc-modified-id="Getting-started-1">Getting started</a></span></li><li><span><a href="#Indexing-and-slicing" data-toc-modified-id="Indexing-and-slicing-2">Indexing and slicing</a></span></li></ul></div>

In [1]:
import torch


In [2]:
# 1D tenzor
x = torch.arange(12, dtype=torch.float32)
x


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

## Getting started

In [3]:
x.numel()

12

In [4]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
# use -1 to infer size for this axis
x.reshape(-1,3)


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [6]:
# Fill with zeros, or ones
torch.zeros((2,3,4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(2,3)


tensor([[-0.8014, -1.7261, -1.0388],
        [ 0.5108,  0.5359, -1.2847]])

In [9]:
torch.tensor([[1,2],[3,4],[5,6]])


tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Indexing and slicing


In [10]:
X = torch.randint(10, (3,4))
X

tensor([[5, 1, 0, 8],
        [2, 6, 1, 9],
        [8, 2, 2, 5]])

In [11]:
X[:1]

tensor([[5, 1, 0, 8]])

In [12]:
X[-1]

tensor([8, 2, 2, 5])

In [13]:
X[-2]

tensor([2, 6, 1, 9])

In [14]:
X[1:3]

tensor([[2, 6, 1, 9],
        [8, 2, 2, 5]])

In [15]:
X[:-1, :]

tensor([[5, 1, 0, 8],
        [2, 6, 1, 9]])

In [1]:
X


NameError: name 'X' is not defined