# Excercises - Chapter 1 PyTorch Basics

In [1]:
import torch

# Create a 5x5 tensor with random values between 0 and 1. Print the tensor and its shape.

tensor = torch.rand(5, 5)
print(tensor)
print(tensor.shape)

tensor([[0.7225, 0.0061, 0.3088, 0.8153, 0.8452],
        [0.9247, 0.8551, 0.8588, 0.2065, 0.2447],
        [0.1421, 0.1797, 0.0358, 0.7419, 0.8806],
        [0.1977, 0.5466, 0.5733, 0.3269, 0.9627],
        [0.0852, 0.9765, 0.5429, 0.5748, 0.3426]])
torch.Size([5, 5])


In [2]:
# Create a 3x3 identity matrix (ones on the diagonal, zeros elsewhere) using PyTorch.

torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [3]:
# Create two 3x3 tensors with random integer values between 1 and 10. Add them element-wise and print the result.

t1 = torch.randint(1, 10, (3, 3))
t2 = torch.randint(1, 10, (3, 3))
print(t1 + t2)


tensor([[ 5,  7,  8],
        [18, 10,  5],
        [ 7, 10,  9]])


In [4]:
# Create a 4x4 tensor with random values between -1 and 1. Multiply each element by 5 and add 2. Print the tensor.

t = torch.randint(-1, 1, (4, 4))
print(t)
t = t * 5
print(t)
t = t + 2
print(t)


tensor([[-1,  0, -1, -1],
        [ 0,  0,  0,  0],
        [-1,  0,  0, -1],
        [ 0,  0,  0,  0]])
tensor([[-5,  0, -5, -5],
        [ 0,  0,  0,  0],
        [-5,  0,  0, -5],
        [ 0,  0,  0,  0]])
tensor([[-3,  2, -3, -3],
        [ 2,  2,  2,  2],
        [-3,  2,  2, -3],
        [ 2,  2,  2,  2]])


## Indexing, Slicing, and Joining