# Data Preprocessing



See also:
https://colab.research.google.com/github/d2l-ai/d2l-pytorch-colab/blob/master/chapter_preliminaries/pandas.ipynb


## Reading dataset

In [62]:
# Create CSV file to play with

import os
os.makedirs(os.path.join('.', 'data', ), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')


In [63]:
# Read CSV file

import pandas as pd

data = pd.read_csv(data_file)
data


NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

## 2.2.2. Data preparation

**Steps in training data processing:**

1. Separate input columns and target values (labels). We can select columns either by name or via integer-location based indexing (iloc).

In [64]:
inputs = data.iloc[:, 0:2]
inputs

NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      NaN

In [65]:
targets = data.iloc[:, 2]
targets


0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

2. Handle bad data using imputation.
- Categorical data - creates separate column for each category.
- Numerical values - replace NaNs with mean values



In [66]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs


NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1

In [67]:
inputs = inputs.fillna(inputs.mean())
inputs # returns pd.DataFrame

NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1

## 2.2.3 Conversion to Tensor format

In [68]:
inputs.values # returns np.ndarray

array([[3., 0., 1.],
       [2., 0., 1.],
       [4., 1., 0.],
       [3., 0., 1.]])

In [69]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(targets.values)
X, y


(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

# Exercises

## Load Tommy.v2 data
