# Initializing Tensors

In [1]:
def describe(x):
    print(f"Type: {x.type()}")
    print(f"Shape/size: {x.shape}")
    print(f"Values: \n{x}\n")


In [2]:
# Creating a tensor in PyTorch with torch.Tensor

import torch

describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [3]:
# Create randomly initialized Tensor
describe(torch.rand(2, 3))  # uniform normal
describe(torch.randn(2, 3))  # random normal


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5989, 0.0592, 0.4879],
        [0.7342, 0.9399, 0.0663]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-1.8501, -0.5239,  2.0302],
        [ 0.0677, -0.7353,  0.2781]])



In [4]:
# Create a tensor with all zeros
describe(torch.zeros(2, 3))

# Create a tensor with all ones
describe(torch.ones(2, 3))

# Create a tensor with some predefined value
describe(torch.full((2, 3), 7))

# Fill existing tensor with some predefined value
x = torch.Tensor(2, 3)
describe(x.fill_(3.14))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[7, 7, 7],
        [7, 7, 7]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])



In [5]:
# Create and initialize from the list
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [6]:
# Create a tensor from NumPy array
import numpy as np

npy = np.random.rand(2, 3)
print(f'npy={npy}\n-----------------')
describe(torch.from_numpy(npy))


npy=[[0.61035344 0.03940025 0.78207613]
 [0.93972577 0.40212611 0.87734535]]
-----------------
Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.6104, 0.0394, 0.7821],
        [0.9397, 0.4021, 0.8773]], dtype=torch.float64)



# Tensor Types and Sizes


In [7]:
# Tensor properties

x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [8]:
x = x.long()
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [9]:
# NOTE that there is a call to different function: torch.tensor() instead of torch.Tensor()
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int64)
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [10]:
x = x.float()
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



# Trensor Operations


In [11]:
x = torch.randn(2, 3)
x = x.long()
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0, -3,  0],
        [ 2, -2,  0]])



In [12]:
# Addition
describe(torch.add(x, x))

describe(x + x)


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0, -6,  0],
        [ 4, -4,  0]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0, -6,  0],
        [ 4, -4,  0]])



### Dimensional operations


In [13]:
x = torch.arange(6)
describe(x)

x = x.view(2, 3)
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [17]:
# Collapse rows (dim 0) by summarizing columns
describe(torch.sum(x, dim=0))

# Collapse columns (dim 1) by summarizing rows
describe(torch.sum(x, dim=1))

# Error, because there is only 2 dimentsions

try:
    describe(torch.sum(x, dim=2))
except IndexError:
    print("Error: `torch.sum(x, dim=2)` : Tensor does not have a third dimension.")


Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])

Error: `torch.sum(x, dim=2)` : Tensor does not have a third dimension.


### Indexing, Slicing, and Joining


In [19]:
# Indexing in python
my_list = [10, 20, 30, 40, 50]

print(my_list[0])  # returns 10
print(my_list[-1])  # returns 50
print(my_list[0:2])  # returns [10, 20]
print(my_list[:2])  # returns [10, 20]
print(my_list[:])  # returns [10, 20, 30, 40, 50]
print(my_list[::2])  # returns [10, 30, 50].  2 is the step size


10
50
[10, 20]
[10, 20]
[10, 20, 30, 40, 50]
[10, 30, 50]


### Indexing and Slicing in NumPy Arrays

In [20]:
import numpy as np

my_array = np.array([10, 20, 30, 40, 50])

# This part is exactly the same as indexing and slicing in python lists
print(my_array[0])  # returns 10
print(my_array[-1])  # returns 50
print(my_array[0:2])  # returns [10, 20]
print(my_array[:])  # returns [10, 20, 30, 40, 50]
print(my_array[::2])  # returns [10, 30, 50].  2 is the step size


10
50
[10 20]
[10 20 30 40 50]
[10 30 50]


In [21]:
# 2D arrays

my_2d_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(my_2d_array)
print(my_2d_array[0, 1])  # returns 20

# access all columns (denoted by :) of the first row (index 0) of the array.
print(my_2d_array[0, :])  # returns [10, 20, 30]

# access all rows (denoted by :) of the second column (index 1) of the array.
print(my_2d_array[:, 1])  # returns [20, 50, 80]


[[10 20 30]
 [40 50 60]
 [70 80 90]]
20
[10 20 30]
[20 50 80]


In [22]:
x = torch.arange(6).view(2, 3)
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [24]:
"""
You can use slicing to extract a subset of a multi-dimensional NumPy array or PyTorch tensor along any dimension. 
The syntax for slicing is similar to that of Python lists, but with multiple indices or ranges separated by commas. For example, consider the following 3D NumPy array:
"""
my_3d_array = np.arange(24).reshape(2, 3, 4)
print(f'my_3d_array.shape={my_3d_array.shape}\n---')
print(f'my_3d_array=\n{my_3d_array}\n---')
print(f'my_3d_array[0, 0, :]=\n{my_3d_array[0, 0, :]}\n---')
print(f'my_3d_array[0, :, 1]=\n{my_3d_array[0, :, 1]}\n---')
print(f'my_3d_array[1, 1, 0:2]=\n{my_3d_array[1, 1, 0:2]}\n---')

my_3d_array.shape=(2, 3, 4)
---
my_3d_array=
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
---
my_3d_array[0, 0, :]=
[0 1 2 3]
---
my_3d_array[0, :, 1]=
[1 5 9]
---
my_3d_array[1, 1, 0:2]=
[16 17]
---


### Indexing, Slicing and Joining in PyTorch


In [25]:
x = torch.arange(12).view(3, 4)
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])



In [26]:
# access a single element at row 1, column 2
print(x[1, 2])  # output: tensor(6)

# extract the first row of the tensor
print(x[0, :])  # output: tensor([1, 2, 3])

# extract the second (i.e. #2) column  of the tensor
print(x[:, 1])  # output: tensor([2, 6, 10])

# extract a sub-tensor from rows 0 to 1 and columns 1 to 2
print(x[0:2, 1:3])  # output: tensor([[1, 2], [5, 6]])


tensor(6)
tensor([0, 1, 2, 3])
tensor([1, 5, 9])
tensor([[1, 2],
        [5, 6]])


In [28]:
# More examples
x = torch.arange(6).view(2, 3)
describe(x)

print(f'x[:1, :]={x[:1, :]}')
print(f'x[:1, :2]={x[:1, :2]}')


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])

x[:1, :]=tensor([[0, 1, 2]])
x[:1, :2]=tensor([[0, 1]])


#### Complex indexing noncontiguous indexing of a tensor

We will use `x` to slice and dice

In [40]:
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])



`index_select` is a PyTorch function that is used to select specific elements from a tensor along a given dimension. In example below:

First we create PyTorch tensor indices that contains the indices of the columns we want to select from `x`. 
In this case, we want to select the first and third columns, so we create a LongTensor with values [0, 2].

Then we apply the `index_select` function to the tensor `x`, specifying the `dim` and index parameters. The `dim` parameter specifies which dimension of `x` to select along (in this case, the second dimension), and the index parameter specifies the indices to select (in this case, the first and third columns). The result is stored in a new tensor called `ind`.

So the resulting tensor `ind` will contain the selected elements of `x` along the second dimension, which in this case are the first and third columns of the original tensor. Note that `index_select` returns a new tensor with the selected elements and does not modify the original tensor `x`.

In [41]:
indices = torch.LongTensor([0,2])
ind = torch.index_select(x, dim=1, index=indices)
describe(ind)


Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])



In [43]:
# Another example

"""
The first line creates a PyTorch tensor indices that contains the indices of the rows we want to select from x. 
In this case, we want to select the first row twice, so we create a LongTensor with values [0, 0].
"""

indices = torch.LongTensor([0,0])
describe(torch.index_select(x, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])

