# Excercises - Chapter 1 PyTorch Basics

In [2]:
import torch

# Create a 5x5 tensor with random values between 0 and 1. Print the tensor and its shape.

tensor = torch.rand(5, 5)
print(tensor)
print(tensor.shape)

tensor([[0.4820, 0.6920, 0.3640, 0.3591, 0.5891],
        [0.4525, 0.1203, 0.0234, 0.4466, 0.4781],
        [0.6412, 0.2364, 0.3694, 0.6885, 0.4123],
        [0.4713, 0.7269, 0.2152, 0.1294, 0.0716],
        [0.9822, 0.5294, 0.7292, 0.2353, 0.8385]])
torch.Size([5, 5])


In [3]:
# Create a 3x3 identity matrix (ones on the diagonal, zeros elsewhere) using PyTorch.

torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [4]:
# Create two 3x3 tensors with random integer values between 1 and 10. Add them element-wise and print the result.

t1 = torch.randint(1, 10, (3, 3))
t2 = torch.randint(1, 10, (3, 3))
print(t1 + t2)


tensor([[11, 10,  8],
        [16, 12, 15],
        [17, 11, 15]])


In [5]:
# Create a 4x4 tensor with random values between -1 and 1. Multiply each element by 5 and add 2. Print the tensor.

t = torch.randint(-1, 1, (4, 4))
print(t)
t = t * 5
print(t)
t = t + 2
print(t)


tensor([[ 0,  0, -1,  0],
        [-1,  0,  0,  0],
        [-1, -1, -1,  0],
        [ 0,  0,  0,  0]])
tensor([[ 0,  0, -5,  0],
        [-5,  0,  0,  0],
        [-5, -5, -5,  0],
        [ 0,  0,  0,  0]])
tensor([[ 2,  2, -3,  2],
        [-3,  2,  2,  2],
        [-3, -3, -3,  2],
        [ 2,  2,  2,  2]])


## Indexing, Slicing, and Joining