In [1]:
import numpy as np




In [2]:
np.random.seed(1)
a = np.random.randn(3, 2)
a, a.shape


(array([[ 1.62434536, -0.61175641],
        [-0.52817175, -1.07296862],
        [ 0.86540763, -2.3015387 ]]),
 (3, 2))

In [3]:
a[:,:1]


array([[ 1.62434536],
       [-0.52817175],
       [ 0.86540763]])

In [4]:
np.random.seed(1)
a = np.random.randn(3, 2, 4)
a, a.shape


(array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
         [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ]],
 
        [[ 0.3190391 , -0.24937038,  1.46210794, -2.06014071],
         [-0.3224172 , -0.38405435,  1.13376944, -1.09989127]],
 
        [[-0.17242821, -0.87785842,  0.04221375,  0.58281521],
         [-1.10061918,  1.14472371,  0.90159072,  0.50249434]]]),
 (3, 2, 4))

In [5]:
a[:,:,0]

array([[ 1.62434536,  0.86540763],
       [ 0.3190391 , -0.3224172 ],
       [-0.17242821, -1.10061918]])

In [6]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
c = np.random.randn(3, 2)
a = np.random.randn(4, 2)
x = np.concatenate((c, a), axis=0)
c,a,x

(array([[ 0.81095167,  1.04444209],
        [-0.40087819,  0.82400562],
        [-0.56230543,  1.95487808]]),
 array([[-1.33195167, -1.76068856],
        [-1.65072127, -0.89055558],
        [-1.1191154 ,  1.9560789 ],
        [-0.3264995 , -1.34267579]]),
 array([[ 0.81095167,  1.04444209],
        [-0.40087819,  0.82400562],
        [-0.56230543,  1.95487808],
        [-1.33195167, -1.76068856],
        [-1.65072127, -0.89055558],
        [-1.1191154 ,  1.9560789 ],
        [-0.3264995 , -1.34267579]]))