# How to use NumPy

In [7]:
import numpy as np


## NumPy Meshgrid



In [37]:
array_cols = [10, 20, 30, 40, 50, 99]
array_rows = [1, 3, 6]

XX, YY = np.meshgrid(array_cols, array_rows)
XX, YY

(array([[10, 20, 30, 40, 50, 99],
        [10, 20, 30, 40, 50, 99],
        [10, 20, 30, 40, 50, 99]]),
 array([[1, 1, 1, 1, 1, 1],
        [3, 3, 3, 3, 3, 3],
        [6, 6, 6, 6, 6, 6]]))

In [40]:
array_cols = [1, 2, 3]
array_rows = [10, 20, 30, 40, 50, 60]

XX, YY = np.meshgrid(array_cols, array_rows, )
XX, YY

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60]]))

In [30]:
YY


array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40],
       [50, 50, 50],
       [99, 99, 99]])