In [12]:
import numpy as np

a = np.random.rand(3,3) < 0.5
d = np.random.rand(3,3)
ad = np.multiply(a,d)
a, d, ad


(array([[ True,  True, False],
        [False,  True, False],
        [ True, False,  True]]),
 array([[0.79016151, 0.85263045, 0.23194777],
        [0.92308361, 0.41226325, 0.12496937],
        [0.79714052, 0.38928804, 0.05544898]]),
 array([[0.79016151, 0.85263045, 0.        ],
        [0.        , 0.41226325, 0.        ],
        [0.79714052, 0.        , 0.05544898]]))