In [86]:
import numpy as np

a = np.random.rand(3,3)
d = (np.random.rand(3,3) < 1).astype(int)
ad = np.multiply(a,d)
a, d, ad

(array([[0.43123235, 0.00908412, 0.49999371],
        [0.87953606, 0.1238875 , 0.84499365],
        [0.31047341, 0.88192871, 0.94297849]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[0.43123235, 0.00908412, 0.49999371],
        [0.87953606, 0.1238875 , 0.84499365],
        [0.31047341, 0.88192871, 0.94297849]]))

In [87]:
np.exp(1)**(-0)

1.0

In [88]:
import numpy as np

W1 = np.array([[2.0, 3, 5, 6], [3, 2, 4, 5]])
W2 = np.array([[2.0,3], [3,2]])
W3 = np.array([[2.0], [3]])

for Wl in [W1, W2, W3]:
    print(np.sum(np.square(Wl)))
    

128.0
26.0
13.0


In [89]:
np.sum([np.sum(np.square(Wl)) for Wl in [W1, W2, W3]])


167.0

In [90]:
W1[0].shape
W1.shape[0], W1.shape[1] 


(2, 4)

In [91]:
np.linalg.norm([2,2])

2.8284271247461903

In [92]:
import numpy as np

m = W1.shape[1]
cc = list(np.random.permutation(m))

W1, cc, W1[:, cc], W1[:, 1:2]


(array([[2., 3., 5., 6.],
        [3., 2., 4., 5.]]),
 [1, 3, 0, 2],
 array([[3., 6., 2., 5.],
        [2., 5., 3., 4.]]),
 array([[3.],
        [2.]]))

In [93]:
l1 = [1, 2, 3, 4, 5]
l2 = ['a', 'b', 'c', 'd', 'e']
[i for i in zip(l1, l2)]


[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]

# TensorFlow

In [94]:
import tensorflow as tf

w=tf.Variable(0, dtype=tf.float32)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)

def train_step():
    with tf.GradientTape() as tape:
        cost = tf.square(w) - 10.0 * w + 25.0  # pyright: ignore[reportOperatorIssue]
        trainable_variables = [w]
        grads = tape.gradient(cost, trainable_variables)
        optimizer.apply_gradients(zip(grads, trainable_variables))

print(w)
train_step()
print(w.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
0.09999931


In [95]:
t = tf.reshape(33, [1])
print(t)

t = tf.reshape(33, [-1])
print(t)

t = tf.reshape([1,2,3], [-1])
print(t)



tf.Tensor([33], shape=(1,), dtype=int32)
tf.Tensor([33], shape=(1,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [96]:
C = 6
for l in [1,2, [1], [0,1,2]]:
    l = tf.reshape(l, [-1])
    print(str(tf.one_hot(l, C)))

tf.Tensor([[0. 1. 0. 0. 0. 0.]], shape=(1, 6), dtype=float32)
tf.Tensor([[0. 0. 1. 0. 0. 0.]], shape=(1, 6), dtype=float32)
tf.Tensor([[0. 1. 0. 0. 0. 0.]], shape=(1, 6), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]], shape=(3, 6), dtype=float32)


In [97]:
tf.zeros((2,2)), tf.ones((2,2))

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [100]:
init = tf.keras.initializers.GlorotNormal(seed=1)  
W1 = tf.Variable(init(shape=(2,2)))
W1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.10181072, -0.39632243],
       [ 0.5073968 , -0.63413197]], dtype=float32)>

In [101]:
tf.keras.activations.relu(W1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.10181072, 0.        ],
       [0.5073968 , 0.        ]], dtype=float32)>