In [2]:
import numpy as np

a = np.random.rand(3,3) < 0.5
d = np.random.rand(3,3)
ad = np.multiply(a,d)
a, d, ad


(array([[ True, False,  True],
        [False, False,  True],
        [ True, False, False]]),
 array([[0.05151974, 0.08457806, 0.65607557],
        [0.05222512, 0.27273875, 0.47037006],
        [0.4890294 , 0.09224402, 0.13777984]]),
 array([[0.05151974, 0.        , 0.65607557],
        [0.        , 0.        , 0.47037006],
        [0.4890294 , 0.        , 0.        ]]))

In [7]:
np.exp(1)**(-0)

1.0

In [ ]:
n