In [72]:
import numpy as np

a = np.random.rand(3,3)
d = (np.random.rand(3,3) < 1).astype(int)
ad = np.multiply(a,d)
a, d, ad










(array([[0.49204657, 0.14525432, 0.22315406],
        [0.79225921, 0.77226014, 0.38562426],
        [0.02362267, 0.22526479, 0.17424872]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[0.49204657, 0.14525432, 0.22315406],
        [0.79225921, 0.77226014, 0.38562426],
        [0.02362267, 0.22526479, 0.17424872]]))

In [7]:
np.exp(1)**(-0)

1.0

In [50]:
import numpy as np

W1 = np.array([[2.0, 3, 5, 6], [3, 2, 4, 5]])
W2 = np.array([[2.0,3], [3,2]])
W3 = np.array([[2.0], [3]])

for Wl in [W1, W2, W3]:
    print(np.sum(np.square(Wl)))
    

128.0
26.0
13.0


In [55]:
np.sum([np.sum(np.square(Wl)) for Wl in [W1, W2, W3]])


167.0

In [75]:
W1[0].shape
W1.shape[0], W1.shape[1] 


(2, 4)

In [77]:
W1, W1/0.5

(array([[2., 3., 5., 6.],
        [3., 2., 4., 5.]]),
 array([[ 4.,  6., 10., 12.],
        [ 6.,  4.,  8., 10.]]))