In [15]:
import numpy as np

a = np.random.rand(3,3)
d = (np.random.rand(3,3) < 1).astype(int)
ad = np.multiply(a,d)
a, d, ad

(array([[0.0135323 , 0.25929352, 0.14582933],
        [0.32646163, 0.84649891, 0.66492442],
        [0.59146668, 0.06348145, 0.90154219]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[0.0135323 , 0.25929352, 0.14582933],
        [0.32646163, 0.84649891, 0.66492442],
        [0.59146668, 0.06348145, 0.90154219]]))

In [16]:
np.exp(1)**(-0)

1.0

In [17]:
import numpy as np

W1 = np.array([[2.0, 3, 5, 6], [3, 2, 4, 5]])
W2 = np.array([[2.0,3], [3,2]])
W3 = np.array([[2.0], [3]])

for Wl in [W1, W2, W3]:
    print(np.sum(np.square(Wl)))
    

128.0
26.0
13.0


In [18]:
np.sum([np.sum(np.square(Wl)) for Wl in [W1, W2, W3]])


167.0

In [19]:
W1[0].shape
W1.shape[0], W1.shape[1] 


(2, 4)

In [20]:
np.linalg.norm([2,2])

2.8284271247461903

In [33]:
import numpy as np

m = W1.shape[1]
cc = list(np.random.permutation(m))

W1, cc, W1[:, cc], W1[:, 1:2]





# list(np.random.permutation(5))










(array([[2., 3., 5., 6.],
        [3., 2., 4., 5.]]),
 [1, 0, 3, 2],
 array([[3., 2., 6., 5.],
        [2., 3., 5., 4.]]),
 array([[3.],
        [2.]]))

In [37]:
W1, W1**2

(array([[2., 3., 5., 6.],
        [3., 2., 4., 5.]]),
 array([[ 4.,  9., 25., 36.],
        [ 9.,  4., 16., 25.]]))